// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

import BookingsController from "./bookings_controller"
application.register("bookings", BookingsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
